### ISSUE TITLE
output about padding oracle attack

### ISSUE THREAD

**Issue by IMhappyZzz** [RUB-NDS/TLS-Attacker#22]
sorry to trouble you ! when I analyse the output of padding oracle attack, I was confused about the  "new value",  I want to know it's meaning in the attacke process .Thank You!

for example the first connection:
![image](https://cloud.githubusercontent.com/assets/24290800/23883254/bcd598fc-08a0-11e7-8dd0-1ec4702f136d.png)

**Comment by ic0ns** [comment]
Hi,
TLS-Attacker uses the concept of ModifiableVariables, which allows TLS-Attacker to modify values at runtime. TLS-Attacker first tries to fill the fields of a Message like in a normal Handshake and then adds Modifications to those Field Values. In your case the ByteArrayExplictValueModification was used, which basically overwrites every value that should be in that field with a predefined value. This is basically what TLS-Attacker shows you here. Meaning "New Value:" is the value that was written by the Modification in the Field.

**Comment by IMhappyZzz** [comment]
Ye，I can't agree any more with you. Maybe  what make me confused  is too  detailed.  I don't understand how  attacker construct messages.
 In my understanding with the case , the record will  be formed by  8 bytes data"74 65 73  74 74 65 73 74 "+20 bytes MAC"79 98 3B 8A FC 52 FD 5B  15 86 2A 97 B7 F2 38 1B AF 24 33 FD "+padding. Then the Padded MACed data before encryption is "00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00" . Why? And  How the  Padded MACed data after encryption goes to 
  73 DC AB 1A 82 09 DF 82  61 8C CA 71 19 E6 F5 9B 
  71 BD 59 90 13 DB 61 38  12 D5 B5 F5 4D D6 63 22 ?
I was so confused about it.  I can't match the output information  with the attack process.Thanks again!

**Comment by jurajsomorovsky** [comment]
The confusion comes probably from the fact how TLS-Attacker constructs the records, see: https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS/src/main/java/de/rub/nds/tlsattacker/tls/record/RecordHandler.java#L127

There are several variables that you can modify during the record processing (https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS/src/main/java/de/rub/nds/tlsattacker/tls/record/Record.java):
- mac
- padding
- paddingLength
- plainRecordBytes

In a typical padding oracle attack, you would probably try to modify the padding bytes, and you would get something like 
``
data || MAC || padding'
``
However, we decided to modify the whole plainRecordBytes, which overwrites the *whole* (data||MAC||padding) string. This gives you more flexibility, because it allows you to trigger cases, where there is not enough space for a correct MAC. This allowed us to find the OpenSSL vulnerability as well: http://web-in-security.blogspot.de/2016/05/curious-padding-oracle-in-openssl-cve.html

So back to your question:
Padded MACed data after encryption
``
73 DC AB 1A 82 09 DF 82 61 8C CA 71 19 E6 F5 9B
71 BD 59 90 13 DB 61 38 12 D5 B5 F5 4D D6 63 22
``
is just a result of encrypting one 
``
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
``
string. The first 16 bytes are an IV, the second 16 bytes are the first ciphertext block. MAC is not used there, even if it was computed.

**Comment by ic0ns** [comment]
The Padded MACed data before encryption is 00 00 ... etc. because in the PaddingOracleAttack TlsAttacker generated different Records which it then uses to send ApplicationMessages. One of those records is generated with a ByteArrayExplicitValueModification with 00 00 00... on PlainRecordBytes. 
Where PlainRecordBytes is ProtocolMessageBytes|Mac|Padding
This means that no matter what is calculated at runtime for ProtocolMessageBytes, Mac or Padding, 00000.... will be inserted in the record for those combined values. I think this is why you are confused. Its an explicit Modification on a Field which in itself is calculated as a concatenation of other Fields ( which might also contain modifiable Variables).
The PlainRecordBytes (which are explicitly set to 00000..) are then encrypted to 
73 DC AB 1A 82 09 DF 82 61 8C CA 71 19 E6 F5 9B
71 BD 59 90 13 DB 61 38 12 D5 B5 F5 4D D6 63 22 .
What you see after is:
ContentType | ProtocolVersion | Length | EncryptedData

**Comment by IMhappyZzz** [comment]
Got it ，Thanks！
