### ISSUE TITLE
TLS-attacker connection issue.

### ISSUE THREAD

**Issue by yeoman313** [RUB-NDS/TLS-Attacker#24]
I wonder how TLS-attacker establish a connection with the server .Does it import socket in any class? I was not able to find clues in this source.
Thank you for help!

**Comment by ic0ns** [comment]
Hello yeoman313,
checkout the TransportHandlers in the Transport Module

**Comment by yeoman313** [comment]
Thank you ,ic0ns.
Why all attack modules imported TransportHandlers more than SimpleTransportHandler
I noticed the latter imports java.net.Socket. What is the relationship between the two java?

**Comment by ic0ns** [comment]
I am not sure what you exactly mean. TransportHandlers are usually responsible for the Opening/Closing/Using of Sockets. Sometimes other Modules need their own Sockets like the EAP Module(deprecated). But usually you should see all Socket related code in the Transport Module

**Comment by yeoman313** [comment]
TransportHandlers.java just import java.io.IOException ;
SimpleTransportHandler.java import java.net.ServerSocket、java.net.Socket、 java.net.SocketException and so on.
I confused why all attack module import  TransportHandlers instead of SimpleTransportHandler.

**Comment by ic0ns** [comment]
Ok now i understand your question. The reason is that TLS-Attacker offers you the possibility to choose what kind of socket you want to send your Data on. The most common distinction is between TCP and UDP. For this purpose you can switch to a UDP TransportHandler. Another example would be EAP, or other protocols where you might need to send some Data before actually using TLS. Therefore TLS-Attacker uses the Abstract TransportHandler. Does this answer your question?

**Comment by yeoman313** [comment]
ic0ns ,thank you for experienced and patient answer .It do help me a lot.
