### ISSUE TITLE
README does not explain how to fuzz

### ISSUE THREAD

**Issue by msoosgds** [RUB-NDS/TLS-Attacker#35]
Hi! How can the system be used to fuzz? Can I create a randomised XML workflow with e.g. Peach and then this could execute it? Is there a set of allowed verbs (and required structures) in the workflow XML? I am happy to write a generative system to create XMLs and then execute them with TLS Attacker and make it open source -- i.e. I am happy to contribute back. I just want to know what's the best way to do this.

Note that I was one of the reviewers for the ACM CCS'16 paper and I'd like to now use the paper :D

**Comment by msoosgds** [comment]
Would it be possible to have an XML that has all the possible options in a structured way? Like for Heartbeat, we'd have:

```
<Heartbeat>
<payloadLength/>
</Heartbeat>
```

So we would know that that's the only thing we can change in Heartbeat. Obviously, there'd be a lot more in ClientHello, etc. That would allow me to create a generator for the XML :)

**Comment by ic0ns** [comment]
Hey,
in the most recent version we removed the fuzzing code since we moved it to a different project (after [TLS-Attacker 1.2](https://github.com/RUB-NDS/TLS-Attacker/releases/tag/v1.2)) which we heavily extended since CCS'16 with more advanced fuzzing strategies and anomaly detection mechanisms in a more structured and generic way. We plan to submit our advances in this field to CCS'18 (hopefully).  I guess the current version could somehow be used with peach fuzzer, but the upcoming fuzzer will probably make this unnecessary :)

If you still want to use the old fuzzer we are happy to assist you in this process.

**Comment by jurajsomorovsky** [comment]
Hey, I am sorry, the newest fuzzing code is not available yet...it is not stable and we do not want to support it for now.
The best way to implement your own fuzzer is to use it directly from the java code. However, I can understand you want to use XML. This can be done in some "hacky" way if you do not have that much time you want to invest in the project.

My fast and hacky approach with the newest TLS-Attacker version would be to generate some basic XML flows (see the TraceTool.jar). You can insert some expliciteValue modifications to the values of the fields. Then, you can use Peach to generate values for these modifications and let TLS-Attacker to execute the workflow.

I assume this will be very slow but can be used to execute some basic evaluations.

With TLS-Attacker 1.2, you can use fuzzing out of the box. The code is buggy and does not support so many TLS features so you will probably not receive such a good test coverage. But we can give it a try if you want :)

**Comment by msoosgds** [comment]
Hey! How does 1.2 support fuzzing out of the box? What is the options I must use? I can't seem to find the option :S Thanks!

**Comment by msoosgds** [comment]
(Also, thanks for the detailed answers, super-useful! I wrote you an email, too :) Thanks again for the detailed descriptions, really kind of you!)

**Comment by ic0ns** [comment]
I could find the old wiki entry for fuzzing. Maybe this explains how to get started.
You can get the old version here:
```
git clone https://github.com/RUB-NDS/TLS-Attacker.wiki.git
cd TLS-Attacker.wiki
git checkout 4a8f92d2369aeb0a933e4b216cbd8d4030f7e9b0
```


Fuzzing
-------------------------------------------------

TLS-Attacker provides currently basic fuzzing capabilities. The best way to use TLS fuzzing is to compile the analyzed code with address sanitizer, for example, OpenSSL as follows:

```bash
cd openssl
./config -fsanitize=address
make -j10
```

This ensures that the server crashes once a boundary violation is detected. See [[TLS Server Compilation|TLS Server Compilation]]

For fuzzing execution you need to download sources and compile TLS-Attacker since you have to rely on some resource files (which are not included in the release version). See [[TLS-Attacker Compilation|TLS-Attacker Compilation]] for more details.

You can then define the properties of the server you are fuzzing. This is done in an XML file:
```xml
<startupCommandsHolder>
    <serverCommand>[link-to-openssl]/apps/openssl </serverCommand>
    <serverPort>51000</serverPort>
    <workflowFolder>resources/fuzzing/workflows</workflowFolder>
    <outputFolder>/tmp/</outputFolder>
    <modifiedVariableTypes>TLS_CONSTANT,LENGTH,COUNT,PUBLIC_KEY,PADDING,SIGNATURE,PLAIN_PROTOCOL_MESSAGE</modifiedVariableTypes>
    <startupCommandsList>
        <startupCommands>
            <fuzzerCommand>simple_fuzzer -connect localhost:$PORT</fuzzerCommand>
            <serverCommandParameters>s_server -quiet -accept $PORT -key resources/rsa1024key.pem -cert resources/rsa1024cert.pem </serverCommandParameters>
            <shortName>openssl-rsa</shortName>
        </startupCommands>
        <startupCommands>
            <fuzzerCommand>simple_fuzzer -connect localhost:$PORT </fuzzerCommand>
            <serverCommandParameters>s_server -quiet -accept $PORT -key resources/ec256key.pem -cert resources/ec256cert.pem </serverCommandParameters>
            <shortName>openssl-ecdhe-ecdsa</shortName>
        </startupCommands>
    </startupCommandsList>
</startupCommandsHolder>
```
If you use this file as an input, TLS-Attacker starts two OpenSSL instances with the given parameters. In this case, one server is configured with RSA and the second with ECDSA.

Set the appropriate reference to your OpenSSL folder, and store the file in `config-multifuzzer-openssl`. Then, you can start TLS-Attacker with a reference to your config file as follows:
```bash
$ cd TLS-Attacker
$ java -jar Runnable/target/TLS-Attacker-1.2.jar -loglevel ERROR multi_fuzzer -startup_command_file config-multifuzzer-openssl
```

TLS-Attacker then starts the TLS servers and then proceeds in two stages. In the first stage, it attempts to execute cryptographic attacks. In the second stage, it attempts to fuzz the server with randomized variable modifications and randomized protocol flows. 

You can see the output of the fuzzing in the folder defined by `outputFolder`. This folder contains invalid TLS flows accepted by the server, or TLS flows causing boundary violations. If you want to re-run a specific TLS flow, you can simply the given workflow file, e.g.:
```bash
$ java -jar Runnable/target/TLS-Attacker-1.2.jar client -workflow_input /tmp/terminated408204.xml
```

Note that the fuzzing implementation is still rather experimental...

**Comment by msoosgds** [comment]
Thanks, this really helped! Thanks for all, cheers!
