### ISSUE TITLE
When server sent ECDHE ServerKeyExchange, client is sending RSA ClientKeyExchange

### ISSUE THREAD

**Issue by saravananmk** [RUB-NDS/TLS-Attacker#45]
Hi,

I am new to this tool.  Just installed and tried the client:

```
$ java -jar TLS-Client.jar -connect www.google.com:443
10:42:59 [main] INFO : DefaultWorkflowExecutor - Connecting to www.google.com:443
10:43:07 [main] INFO : SendAction - Sending messages (client): CLIENT_HELLO,
10:43:09 [main] INFO : ReceiveAction - Received Messages (client): SERVER_HELLO, CERTIFICATE, ECDHE_SERVER_KEY_EXCHANGE, SERVER_HELLO_DONE,
10:43:09 [main] INFO : SendAction - Sending messages (client): RSA_CLIENT_KEY_EXCHANGE, CHANGE_CIPHER_SPEC, FINISHED,
10:43:09 [main] INFO : ReceiveAction - Received Messages (client): Alert(FATAL,DECODE_ERROR),

```

It received ECDHE server key exchange, but as a client it is sending RSA client key exchange which is wrong and hence the connection is failing.  It is supposed to send ECDHE client key exchange.  Am I missing some thing here ?

with regards,
Saravanan

**Comment by ic0ns** [comment]
Hey Saravan,
You are expieriencing this issue:
> Note: If this Handshake fails, it is probably because you did not specify a concrete cipher suite. TLS-Attacker will not completely respect server selected cipher suites.

TLS-Attacker WorkflowTraces are statically constructed when you start the TLS-Client. Per default TLS-Attacker will create a Workflow which corresponds to the default Ciphersuite, which is an RSA Ciphersuite. 
You can specify different cipherSuites with the `-cipher` command like this:
```java -jar TLS-Client.jar -connect somehost:port -cipher TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA``` 
(or some other CipherSuite). Otherwise you could also create your WorkflowTrace manually to send the correct KeyExchange Message. 
cheers
Robert

**Comment by saravananmk** [comment]
Hi Robert,

I am very sorry for not reading the entire README.md before trying the tool.  As soon as I read the first  client example:

> You can run TLS-Attacker as a client with the following command:
> 
> ```
> $ cd apps
> $ java -jar TLS-Client.jar -connect [host:port]
> ```

I am tempted to try it first.   Missed to read that "Note:" you quoted which was present in the later part of the README.md.

Thank you so much for the clarification.  

with regards,
Saravanan

**Comment by ic0ns** [comment]
No worries :)
