### ISSUE TITLE
Is TLS Test Suite feature still available in TLS-Attacker 2.8

### ISSUE THREAD

**Issue by b1u2** [RUB-NDS/TLS-Attacker#55]
Hi, 

I am using TLS-Client, added some modifiableVariables to a custom workflow.xml and i rightly receive a ReceiveAction - Received messages (client): Alert(FATAL, BAD_RECORD_MAC) in the server response (from a mbedTLS server).

With reference to your paper "Systematic Fuzzing and Testing of TLS Libraries" 
Chapter 8.1 Usage of Assertions. 

I added the following tags in my custom workflow.xml

<Alert>
  <messageIssuer>SERVER</messageIssuer>
  <level>
   <assertEquals>2</assertEquals>
  </level>
  <description>
    <assertEquals>20</assertEquals>
 </description>
</Alert>

However, I am still receiving the error message ReceiveAction - Received messages (client): Alert(FATAL, BAD_RECORD_MAC).

Q1) Is the TLS Test Suite feature still available in TLS-Attacker 2.8?
Q2) If yes to Q1, am I doing it correctly to blacklist the error message(s) to ensure that the protocol flow continue to succeed?

Thanks for your reply!

**Comment by ic0ns** [comment]
Hey,
you are hitting a weak spot with that question :) .With TLS-Attacker 2.0 we dropped most of the testsuite, since the sturctural changes made the code very hard to maintain. The assertion concept is still in the ModifiableVariable package, so you could technically use it, but it is currently not used in the applications we ship (to the best of my knowledge).  Personally, i did not work with assertions since I started working with the project. I currently see the applications we ship with TLS-Attacker more or less as examples of how to use TLS-Attacker as a library. Thats why the fuzzer and the testsuite (as well as EAP support) are currently missing. I had a student reimplement the testsuite, but the implementation is not yet production ready and not publically available (this will probably not change so fast). I think with medium efforts its possible to get the assertion validation back into the TLS-Client, but i think you would need to write some code atleast. 

The old version is still here on github, but obviously lacks the new features. I will put the reintegration of the assertion concept on my todo list.

**Comment by b1u2** [comment]
Hi iC0ns

Thanks for your prompt and candid reply! 

May I check with you on how does the current TLS-Attacker process the raw server responses and categorise them into generic TLS messages such as CLIENT_HELLO, SERVER_HELLO, CHANGE_CIPHER_SPEC  or even error messages like Alert(FATAL, UNEXPECTED_MESSAGE) etc. May I know which TLS module (TLS-Core?) and which .java files(s) does the processing? Thanks!

**Comment by ic0ns** [comment]
All of the TLS protocol is implemented in the Core module. The parsing logic is not super simple, since the record layer/ fragmentation etc is involved. But you can probably find the classes you are looking for [here](https://github.com/RUB-NDS/TLS-Attacker/tree/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol) and [here](https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/workflow/action/executor/ReceiveMessageHelper.java)

**Comment by b1u2** [comment]
Thank you! Your comments are v helpful.
