### ISSUE TITLE
X25519 in TLS 1.2

### ISSUE THREAD

**Issue by SidolFreiburg** [RUB-NDS/TLS-Attacker#60]
Hello!

When we try to use the X25519 Curve with TLS Protocol Version 1.2, we get the following error:

```
java.lang.UnsupportedOperationException: The provided curve 'ECDH_X25519' is not supported.
 	at de.rub.nds.tlsattacker.core.crypto.ec.CurveFactory.getCurve(CurveFactory.java:81)
 	at de.rub.nds.tlsattacker.core.crypto.ec.Point.createPoint(Point.java:55)
 	at de.rub.nds.tlsattacker.core.protocol.handler.ECDHEServerKeyExchangeHandler.adjustECParameter(ECDHEServerKeyExchangeHandler.java:64)
 ... 
```
In [NamedGroup.java](https://github.com/RUB-NDS/TLS-Attacker/blob/be5ea4ad513883aa909147b6262b2ffca3845ce5/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/constants/NamedGroup.java#L279) the curve has been marked as implemented. Are you planning to support the Curve in future versions of the TLS-Attacker?

Many thanks and best regards,
Matthias

**Comment by ic0ns** [comment]
Hey Matthias,
X25519 and X448 were supposed to work in this version, but due to a silly bug are not functional. I already have a (temporary) fix for this. I pushed it to the https://github.com/RUB-NDS/TLS-Attacker/tree/montgomeryCurveFix branch. 
I will merge it into the master branch in the near future.
cheers
Robert

**Comment by SidolFreiburg** [comment]
Hey Robert,

Thanks for the quick answer! I'll wait for the next release then!
