### ISSUE TITLE
Could not parse provided host

### ISSUE THREAD

**Issue by FaheemBhatti** [RUB-NDS/TLS-Attacker#65]
![image](https://user-images.githubusercontent.com/50632975/69733582-d7350c80-112d-11ea-8f19-13ea89b366f2.png)

Hi Sir, i am trying to check drown vulnerability with DrownAttakcer.isVulnerable() method and it is returning me with message displaying could not parse provided host:null

**Comment by ic0ns** [comment]
Hey,
the problem is that you did not tell the DrownCommandConfig which host it is supposed to check. This is different to your normal instantiation, as the DrownCommandConfig is usually invoked from the command line. The DrownCommandConfig contains a ClientDelegate, which you have to insert the host and port  you want to scan into. For an example on how to do this check the TLS-Scanner:
[https://github.com/RUB-NDS/TLS-Scanner/blob/master/src/main/java/de/rub/nds/tlsscanner/probe/DrownProbe.java](https://github.com/RUB-NDS/TLS-Scanner/blob/master/src/main/java/de/rub/nds/tlsscanner/probe/DrownProbe.java)

**Comment by FaheemBhatti** [comment]
Thank you so much for guidance, i'll try to get it sorted :)

**Comment by FaheemBhatti** [comment]
![image](https://user-images.githubusercontent.com/50632975/69788484-edd77400-11be-11ea-9ba9-83512e6e5573.png)

Thankx a lot for helping, it is good now, also please do let me know if we can initialize handshake from server side

**Comment by ic0ns** [comment]
Ehm - I am not sure what you mean. TLS cannot be initialized from the server side. If you want to use TLS-Attacker as a TLS-Server you can orient yourself on our example TLS-Server application:
 [https://github.com/RUB-NDS/TLS-Attacker/tree/master/TLS-Server/src/main/java/de/rub/nds/tlsattacker/server](https://github.com/RUB-NDS/TLS-Attacker/tree/master/TLS-Server/src/main/java/de/rub/nds/tlsattacker/server)

**Comment by FaheemBhatti** [comment]
Thank you for the response Sir :) really helpful
