### ISSUE TITLE
How can TLS-Attacker as client invoke TLS-Attacker Server

### ISSUE THREAD

**Issue by FaheemBhatti** [RUB-NDS/TLS-Attacker#69]
Hello,
I want TLS-Attacker Client to hit TLS-Attacker server. i have configured client with different certificates which TLS-Attacker send to server, previously it was with apache server. Now to make testing from both ways i want to test client side as well for which i have to configure some certificates on server side as well, but the workflow is not executing as expected.

My server Class:
![image](https://user-images.githubusercontent.com/50632975/72890122-872f8c00-3d11-11ea-979d-bd5c30c886a0.png)

My client Class: 
![image](https://user-images.githubusercontent.com/50632975/72890313-ea212300-3d11-11ea-9577-2bac1d719e44.png)

Can you please guide is there something missing or any other requirement of TLS-Attacker which has to be filled to invoke server from client class
I didn't find anything related to server workflow in documentation 
Thank you

**Comment by ic0ns** [comment]
It looks like your client is not speaking TLS - are you trying to speak HTTP accidentally?

**Comment by FaheemBhatti** [comment]
Nope, i am using HTTPS, what i guess the issue is TLS-Server is not taking any default certificate or there is no certificate available with server to send in Server Hello Message.

**Comment by ic0ns** [comment]
The problem is that TLS-Attacker does not even receive a ClientHello - instead it complains that the first record it received does not even follow the record structure. That is why you get this weired: "Not decrypting received non Record:Blobrecord". TLS-Attacker is not passing the data to the null cipher, as it does not know what this is. Is your client using the SSLv2 compatibility mode? Could you provide a pcap of the conversation or activate debug mode?

**Comment by FaheemBhatti** [comment]
Sir,
Right now i am using TLS-Client.jar to hit server with certificate configured 
![image](https://user-images.githubusercontent.com/50632975/72894134-ed6cdc80-3d1a-11ea-8f45-7ed18e079788.png)

**Comment by ic0ns** [comment]
I see, this might be a timing issue then. As you server indicates that it did send a CCS, FIN - but since you cannot see them on the client side (or anything at all) it might be that the server is too slow to respond and that the TLS-Client simply stops waiting for more messages. It is tricky to test TLS-Attacker with TLS-Attacker... Try increasing the `-timeout`

**Comment by FaheemBhatti** [comment]
Sure ,
Thank you :)
