### ISSUE TITLE
TLS-Client.jar is not sending TLS1.3 Handshake with "-version TLS13"

### ISSUE THREAD

**Issue by sajualways** [RUB-NDS/TLS-Attacker#76]
I have installed TLS-Attacker-3.0b and when i use below command to test against my server, I don't see TLS1.3 Handshake in the trace

TLS-Attacker-3.0b/apps
java -jar TLS-Client.jar -connect <IP>:<PORT> -version TLS13

When I took the wireshark trace, It was sending and negotiating only TLS12 handshake only.
I don't see any TLS Extensions related to TLS1.3 going in Client Hello.

Is this not supported yet or should i give some other options to test TLS1.3 Handshake ?

I gave the above "-version" based on this below possible values.

    -version
      Highest supported protocol version
      Possible Values: [SSL2, SSL3, TLS10, TLS11, TLS12, TLS13, TLS13_DRAFT14, TLS13_DRAFT15, TLS13_DRAFT16, TLS13_DRAFT17, TLS13_DRAFT18, TLS13_DRAFT19, TLS13_DRAFT20, TLS13_DRAFT21, TLS13_DRAFT22, TLS13_DRAFT23, TLS13_DRAFT24, TLS13_DRAFT25, TLS13_DRAFT26, TLS13_DRAFT27, TLS13_DRAFT28, DTLS10, DTLS12]

**Comment by ic0ns** [comment]
Hey,
this is because of TLS-Attackers configuration system. Internally, TLS-Attacker has a _Config.java_  class which tells TLS-Attacker how to create messages. This Config is defaulting to TLS 1.2ish handshakes. If you change the protocol version with the command line, you are just changing one (i think its just one at least) value in the config, namely the highest supported version of the client. To be able to do a TLS 1.3 handshake you need to change more than that. As you need additional extensions, and also different actions. 
To be able to do a TLS 1.3 handshake you need a TLS 1.3 compatible Config. We added configs for TLS 1.3 to the resources/ folder. You can load them with the `-config` flag of TLS-Client.jar. That should do the trick.

Note: These Config files were manually crafted a while ago. It might be that some of the defined variable names changed with version updates of TLS-Attacker. If you find that this approach still does not work. Please comment here and I try to fix it.

**Comment by sajualways** [comment]
Ok...thanks...so we can have our own -config file and change the default vaules such as key share algorithm...etc...right?

Also how to get the names of the key share group and algos, say for example if i need "prime256v1" key share below

<defaultSelectedNamedGroup>ECDH_X25519</defaultSelectedNamedGroup>

**Comment by ic0ns** [comment]
Its the name of the constant within TLS-Attacker. For a full list check here:
[https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/constants/NamedGroup.java](https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/constants/NamedGroup.java)
Besides, I wrote a Tutorial last year which might help you:
[https://web-in-security.blogspot.com/2019/03/playing-with-tls-attacker.html](https://web-in-security.blogspot.com/2019/03/playing-with-tls-attacker.html)

**Comment by sajualways** [comment]
Thanks a lot !!
